apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /tmp/pv004
    type: ""
  persistentVolumeReclaimPolicy: Recycle